### ISSUE TITLE
Separate resources directory from results directory

### ISSUE THREAD

**Issue by daniagudelos** [SES-fortiss/SmartGridCoSimulation#16]
**Justification:** With current configuration there is not a clear separation of project inputs and outputs. Results are versioned because they are generated in the resources file (bad practice).

**Current configuration:** 

res/ contains the following: 
-  default consumption files
-  directory "results" with results csvs
-  directory "opcconfig" with option configuration files

Ideally, only the resources that the project use should be in the "resource" directory. Therefore, "opcconfig" and "results" should be moved to another directory. 

**Suggestion for directory structure:**

- Source code: 
memapServer/src/main/java/linprogMPC

-  Resources directory:
memapServer/src/main/java/resources

-  Configuration and results directory:
~/output/opcconfig
~/output/results

Created in the execution directory.

This is the current configuration of memapBasis and memapGui

**Comment by highvight** [comment]
Most of the files in the 'res' are not necessary at all for the main program, but are mainly used to run the examples. I'd suggest to put all of them in '\res\examples\opcua' and 'res\examples\csv' respectively at some point and delete them all together in the future.

I agree that '\res' should not contain result files.
