### ISSUE TITLE
Increasing costs for storages - still necessary after standbyLoss implementation?

### ISSUE THREAD

**Issue by johburger** [SES-fortiss/SmartGridCoSimulation#161]
In the MILPProblemWithConnection class where the objective function is set, the costs for storage charging or discharging is increased for future time steps within the horizon. This is also included in MILPProblemNoConnections
Denis mentioned, that this improved results. However, after the implementation of the standby losses, is it still necessary?

**Comment by bytschkow** [comment]
Yes - indeed, we do not need that anymore. We can remove that part in future.

**Comment by bytschkow** [comment]
it is removed in the current version. Can this issue be closed?
